# Generated by Django 2.2.4 on 2020-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_phone', models.IntegerField()),
                ('student_email', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=60)),
                ('student_city', models.CharField(max_length=20)),
                ('student_street', models.CharField(max_length=20)),
            ],
        ),
    ]
