# Generated by Django 2.2.4 on 2020-01-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=50)),
                ('login_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
