# Generated by Django 2.2.4 on 2020-01-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stport', '0002_login_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='student_recentbooks',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
