# Generated by Django 2.2.4 on 2020-01-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stport', '0003_student_info_student_recentbooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='student_recentbooks',
            new_name='student_issue',
        ),
    ]
