# Generated by Django 2.2.4 on 2020-01-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stport', '0004_auto_20200113_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_info',
        ),
    ]
