# Generated by Django 2.2.4 on 2020-01-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stport', '0006_book_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_info',
        ),
    ]
