# Generated by Django 2.2.4 on 2020-01-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stport', '0007_delete_book_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
