# Generated by Django 2.2.4 on 2020-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='book_student',
        ),
        migrations.AddField(
            model_name='book_info',
            name='bk_student_id',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
