# Generated by Django 2.2.4 on 2020-01-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0005_auto_20200113_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='lib_admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=50)),
                ('a_phone', models.IntegerField()),
                ('a_email', models.CharField(max_length=50)),
                ('a_password', models.CharField(max_length=60)),
            ],
        ),
    ]
