# Generated by Django 2.2.4 on 2020-01-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0007_book_info_book_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='book_lot',
            field=models.IntegerField(default=0),
        ),
    ]
