# Generated by Django 2.2.4 on 2020-01-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0008_auto_20200116_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=300)),
            ],
        ),
    ]
