# Generated by Django 2.2.4 on 2020-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0009_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='book_lot',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
