# Generated by Django 2.2.4 on 2020-01-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0010_auto_20200116_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice',
            new_name='notice1',
        ),
    ]
